# fly.toml app configuration file generated for rezzo-deploy-fly on 2025-07-17T13:11:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rezzo-deploy-fly'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
